### ISSUE TITLE
Installing and Using Git: package installation missing

### ISSUE THREAD

**Issue by jonathan-reisdorf** [OnionIoT/Onion-Docs#19]
For the `git-http` package to correctly work, the `ca-bundle` package is required as well. This is not documented unfortunately. The command in the docs should instead be: `opkg install git git-http ca-bundle`

**Comment by greenbreakfast** [comment]
Fixed! We only tested with public repos, looks like `ca-bundle` is required with private repos.
Thanks for the heads up!

**Comment by jonathan-reisdorf** [comment]
Hi, when going to https://wiki.onion.io/Tutorials/Using-Git I still can't see that `ca-bundle` is mentioned.

**Comment by greenbreakfast** [comment]
The new documentation site is https://docs.onion.io

Go to https://docs.onion.io/omega2-docs/installing-and-using-git.html and you'll see `ca-bundle` in step 3
